[project]
name = "testing-tricks"
version = "0.1.0"
description = "Python testing tricks"
readme = "README.md"
requires-python = ">=3.13.3"
authors = [{name = "Jeffrey S. Haemer", email = "jeffrey.haemer@gmail.com"}]
license = "MIT"
dependencies = [
    "mutmut>=3.2.3",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "ruff>=0.11.11",
]
[tool.pytest.ini_options]
addopts = """
    --cov=.
    --cov-report term-missing
    --cov-report html:htmlcov
"""
[tool.coverage.run]
omit = [
    "__init__.py",
    "tests/*",
    "main.py",
]
[tool.mutmut]
# Specify the path(s) to your source code file(s) relative to the project root.
# Use "." for the current directory, or list specific files.
paths_to_mutate = ["compares.py"]
# Command to run your tests from the project root directory.
runner = "pytest tests/"
